use super::{stake_credential_hash, LedgerState, StakeSnapshot};
use std::collections::HashMap;
use std::sync::Arc;
use torsten_primitives::hash::Hash32;
use torsten_primitives::time::EpochNo;
use torsten_primitives::value::Lovelace;
use tracing::{debug, info, warn};

impl LedgerState {
    /// Process an epoch transition
    ///
    /// Follows Haskell's NEWEPOCH STS rule ordering:
    /// 1. Apply any pending reward update carried over from old snapshots (backward compat)
    /// 2. Rotate snapshots: go = set, set = mark, mark = new
    /// 3. Compute new reward update using the freshly-rotated SET snapshot and apply IMMEDIATELY
    /// 4. Process retirements, governance, nonce, etc.
    ///
    /// # RUPD timing (matches Haskell's NEWEPOCH/TICK rules exactly)
    ///
    /// In Haskell, the RUPD is pulsed *during* epoch E using `ssStakeGo` — the go snapshot
    /// that was installed at the E-1 -> E boundary.  The completed RUPD is applied at the
    /// E -> E+1 boundary during the SAME SNAP rotation.
    ///
    /// At the E -> E+1 boundary the SNAP rotation fires FIRST:
    ///   go  = old set  (epoch E-1 data)
    ///   set = old mark (epoch E data — the epoch that JUST ended)
    ///   mark = newly built
    ///
    /// The completed RUPD was pulsed during epoch E using the go snapshot that existed at
    /// the START of epoch E, which is the snapshot promoted to go at the E-1 -> E boundary.
    /// That snapshot contained epoch E-1 data.  After the E -> E+1 rotation the same data
    /// now sits in the NEW go position.
    ///
    /// HOWEVER: at the very first epoch boundary (0 -> 1) there was no prior set snapshot
    /// (set = None before the boundary), so after rotation go = None.  Haskell still fires
    /// the RUPD at this boundary using the epoch-0 snapshot, which is now in the SET position
    /// (old mark = epoch-0 data).
    ///
    /// Cross-checking against Koios on-chain data (preview testnet):
    ///   initial_reserves = 15_000_000_000_000_000 (45T max - 30T Byron genesis UTxOs)
    ///   expansion_0→1   = floor(0.003 × 15T × 4320/4320) = 45_000_000_000_000
    ///   treasury_0→1    = floor(0.2  × 45_000_000_000_000) = 9_000_000_000_000
    ///   Koios epoch 1 treasury = 9_000_000_000_000  ← exact match
    ///
    /// The RUPD at epoch 0→1 uses the epoch-0 snapshot's block count (4320 blocks, eta=1.0).
    /// After the 0→1 rotation that snapshot is in the SET position (old mark = epoch-0 data).
    /// Using the GO position (old set = None) would skip the RUPD entirely — that is the bug
    /// that produces 14T treasury (2.16×) instead of the canonical 6.51T.
    ///
    /// Therefore: RUPD must use `self.snapshots.set` (epoch-just-ended data, matching what
    /// Haskell's RUPD pulsed on), NOT `self.snapshots.go` (epoch-2-ago data, skipped at
    /// epoch 0→1 because go is None for the first two boundaries).
    pub fn process_epoch_transition(&mut self, new_epoch: EpochNo) {
        debug!("Epoch transition: {} -> {}", self.epoch.0, new_epoch.0);

        // Step 1: Apply any reward update carried over from snapshots written by the OLD
        // deferred-RUPD code path.  For snapshots generated by the corrected code this is
        // always a no-op (pending_reward_update is always None after this function returns).
        self.apply_pending_reward_update();

        // Rotate snapshots: go = set, set = mark, mark = built below.
        // Rotation must happen BEFORE computing RUPD so that:
        //   new go  = old set = epoch E-1 data (2 epochs stale relative to new_epoch)
        //   new set = old mark = epoch E data  (1 epoch stale — the epoch that just ended)
        // The RUPD uses the new SET (old mark = epoch-just-ended data) to match Haskell.
        self.snapshots.go = self.snapshots.set.take();
        self.snapshots.set = self.snapshots.mark.take();

        // Rebuild stake distribution from the full UTxO set at epoch boundaries.
        // During fast replay (needs_stake_rebuild=false), skip the expensive full
        // UTxO scan. During live sync (needs_stake_rebuild=true, the default),
        // always rebuild to ensure correctness and prevent incremental drift.
        // Note: needs_stake_rebuild stays true once set — every live epoch boundary rebuilds.
        if self.needs_stake_rebuild {
            self.rebuild_stake_distribution();
        }

        // Per Cardano spec, total stake = UTxO-delegated stake + reward account balance.
        // Pre-size to the number of distinct pools (upper-bounded by delegations).
        let mut pool_stake: HashMap<torsten_primitives::hash::Hash28, Lovelace> =
            HashMap::with_capacity(self.pool_params.len());
        for (cred_hash, pool_id) in self.delegations.iter() {
            let utxo_stake = self
                .stake_distribution
                .stake_map
                .get(cred_hash)
                .copied()
                .unwrap_or(Lovelace(0));
            let reward_balance = self
                .reward_accounts
                .get(cred_hash)
                .copied()
                .unwrap_or(Lovelace(0));
            let total_stake = Lovelace(utxo_stake.0 + reward_balance.0);
            *pool_stake.entry(*pool_id).or_insert(Lovelace(0)) += total_stake;
        }

        // Build per-credential stake including reward balances. Clone the
        // stake_map as the base and fold in reward account balances. The clone
        // already carries the correct capacity from the original map.
        let mut snapshot_stake = self.stake_distribution.stake_map.clone();
        for (cred_hash, reward) in self.reward_accounts.iter() {
            if reward.0 > 0 {
                *snapshot_stake.entry(*cred_hash).or_insert(Lovelace(0)) += *reward;
            }
        }

        let total_utxo_stake: u64 = self
            .stake_distribution
            .stake_map
            .values()
            .fold(0u64, |acc, l| acc.saturating_add(l.0));
        let total_pool_stake: u64 = pool_stake
            .values()
            .fold(0u64, |acc, l| acc.saturating_add(l.0));
        debug!(
            epoch = new_epoch.0,
            credentials = self.stake_distribution.stake_map.len(),
            delegations = self.delegations.len(),
            pools = pool_stake.len(),
            total_utxo_stake_ada = total_utxo_stake / 1_000_000,
            total_pool_stake_ada = total_pool_stake / 1_000_000,
            "Epoch snapshot: stake distribution rebuilt from UTxO set"
        );

        self.snapshots.mark = Some(StakeSnapshot {
            epoch: new_epoch,
            delegations: Arc::clone(&self.delegations),
            pool_stake,
            pool_params: Arc::clone(&self.pool_params),
            stake_distribution: Arc::new(snapshot_stake),
            // Capture the epoch that just ended's performance data.
            // After three rotations this reaches "go" and is used by
            // calculate_rewards() — matching Haskell's RUPD rule.
            epoch_fees: self.epoch_fees,
            epoch_block_count: self.epoch_block_count,
            epoch_blocks_by_pool: Arc::clone(&self.epoch_blocks_by_pool),
        });

        // Step 3: Compute the reward update from the newly-rotated SET snapshot and
        // apply it immediately — matching Haskell's NEWEPOCH rule where RUPD is
        // completed and applied in the same boundary transition.
        //
        // After the rotation above:
        //   set = old mark = stake/performance data from epoch E (the epoch just ended)
        //
        // At epoch 0→1: go = None (old set was None), set = epoch-0 snapshot.
        // Using set ensures the RUPD fires at the FIRST epoch boundary (0→1) with
        // the epoch-0 block count (4320 blocks, eta=1.0), producing the 9B treasury
        // that Koios on-chain data confirms.  Using go would skip the first two
        // RUPDs entirely (go is None for boundaries 0→1 and 1→2), causing 2.16× drift.
        //
        // Note: `calculate_rewards` uses `self.reserves` which was already updated by
        // `apply_pending_reward_update` at step 1, matching Haskell's ordering.
        if let Some(set_snapshot) = self.snapshots.set.clone() {
            let rupd = self.calculate_rewards(&set_snapshot);
            // Apply immediately: no deferral, no pending_reward_update accumulation.
            self.reserves.0 = self.reserves.0.saturating_sub(rupd.delta_reserves);
            self.treasury.0 = self.treasury.0.saturating_add(rupd.delta_treasury);
            let mut total_applied = 0u64;
            for (cred_hash, reward) in &rupd.rewards {
                if reward.0 > 0 {
                    *Arc::make_mut(&mut self.reward_accounts)
                        .entry(*cred_hash)
                        .or_insert(Lovelace(0)) += *reward;
                    total_applied += reward.0;
                }
            }
            debug!(
                epoch = new_epoch.0,
                accounts = rupd.rewards.len(),
                total_applied,
                treasury_delta = rupd.delta_treasury,
                reserves_delta = rupd.delta_reserves,
                "RUPD applied at epoch boundary using set snapshot (Haskell-compatible)"
            );
        }

        // Process pending pool retirements for this epoch
        if let Some(retiring_pools) = self.pending_retirements.remove(&new_epoch) {
            let pool_deposit = self.protocol_params.pool_deposit;
            for pool_id in &retiring_pools {
                // Refund pool deposit to operator's registered reward account
                if let Some(pool_reg) = Arc::make_mut(&mut self.pool_params).remove(pool_id) {
                    let op_key = Self::reward_account_to_hash(&pool_reg.reward_account);
                    *Arc::make_mut(&mut self.reward_accounts)
                        .entry(op_key)
                        .or_insert(Lovelace(0)) += pool_deposit;
                    debug!(
                        "Pool retired at epoch {}: {} (deposit {} refunded)",
                        new_epoch.0,
                        pool_id.to_hex(),
                        pool_deposit.0
                    );
                } else {
                    debug!(
                        "Pool retired at epoch {}: {} (no params found)",
                        new_epoch.0,
                        pool_id.to_hex()
                    );
                }
            }
        }

        // Clean up retirements from past epochs (shouldn't happen but be safe)
        self.pending_retirements
            .retain(|epoch, _| *epoch >= new_epoch);

        // Apply pre-Conway protocol parameter update proposals (PPUP rule).
        // In Shelley-Babbage, genesis delegates submit update proposals targeting epoch E.
        // At the epoch boundary E -> E+1, proposals targeting E are evaluated:
        // if enough distinct genesis delegates proposed updates (>= update_quorum),
        // their proposals are merged and applied to take effect in epoch E+1.
        // Note: self.epoch still holds the OLD epoch at this point (updated at end).
        if let Some(proposals) = self.pending_pp_updates.remove(&self.epoch) {
            // Count distinct proposers (genesis delegate hashes)
            let mut proposer_set: std::collections::HashSet<Hash32> =
                std::collections::HashSet::with_capacity(proposals.len());
            for (genesis_hash, _) in &proposals {
                proposer_set.insert(*genesis_hash);
            }
            let distinct_proposers = proposer_set.len() as u64;

            if distinct_proposers >= self.update_quorum {
                // Merge all proposals: later proposals override earlier ones per field
                let mut merged = torsten_primitives::transaction::ProtocolParamUpdate::default();
                for (_, ppu) in &proposals {
                    // Merge each field: if the proposal sets it, override
                    macro_rules! merge_field {
                        ($field:ident) => {
                            if ppu.$field.is_some() {
                                merged.$field = ppu.$field.clone();
                            }
                        };
                    }
                    merge_field!(min_fee_a);
                    merge_field!(min_fee_b);
                    merge_field!(max_block_body_size);
                    merge_field!(max_tx_size);
                    merge_field!(max_block_header_size);
                    merge_field!(key_deposit);
                    merge_field!(pool_deposit);
                    merge_field!(e_max);
                    merge_field!(n_opt);
                    merge_field!(a0);
                    merge_field!(rho);
                    merge_field!(tau);
                    merge_field!(min_pool_cost);
                    merge_field!(ada_per_utxo_byte);
                    merge_field!(cost_models);
                    merge_field!(execution_costs);
                    merge_field!(max_tx_ex_units);
                    merge_field!(max_block_ex_units);
                    merge_field!(max_val_size);
                    merge_field!(collateral_percentage);
                    merge_field!(max_collateral_inputs);
                    merge_field!(protocol_version_major);
                    merge_field!(protocol_version_minor);
                }
                // Log protocol version change if applicable
                if merged.protocol_version_major.is_some()
                    || merged.protocol_version_minor.is_some()
                {
                    info!(
                        "Protocol     version change {}.{} -> {}.{} (epoch {})",
                        self.protocol_params.protocol_version_major,
                        self.protocol_params.protocol_version_minor,
                        merged
                            .protocol_version_major
                            .unwrap_or(self.protocol_params.protocol_version_major),
                        merged
                            .protocol_version_minor
                            .unwrap_or(self.protocol_params.protocol_version_minor),
                        new_epoch.0,
                    );
                }
                if let Err(e) = self.apply_protocol_param_update(&merged) {
                    warn!(
                        epoch = new_epoch.0,
                        error = %e,
                        "Pre-Conway protocol parameter update rejected"
                    );
                } else {
                    debug!(
                        epoch = new_epoch.0,
                        proposers = distinct_proposers,
                        "Pre-Conway protocol parameter update applied"
                    );
                }
            } else {
                debug!(
                    epoch = new_epoch.0,
                    proposers = distinct_proposers,
                    quorum = self.update_quorum,
                    "Pre-Conway protocol parameter update: insufficient quorum"
                );
            }
        }
        // Clean up proposals targeting past epochs (already applied above).
        // Keep proposals targeting new_epoch or later — they'll be applied at
        // the NEXT epoch boundary (new_epoch -> new_epoch+1).
        self.pending_pp_updates
            .retain(|epoch, _| *epoch >= new_epoch);

        // Ratify governance proposals that have met their voting thresholds
        self.ratify_proposals();

        // Expire governance proposals that have passed their lifetime
        // and refund deposits to the return address
        let expired: Vec<torsten_primitives::transaction::GovActionId> = self
            .governance
            .proposals
            .iter()
            // Per Haskell: `gasExpiresAfter < reCurrentEpoch` — proposals are active
            // through their expires_epoch and expire at the NEXT epoch boundary.
            .filter(|(_, state)| state.expires_epoch < new_epoch)
            .map(|(id, _)| id.clone())
            .collect();
        if !expired.is_empty() {
            for action_id in &expired {
                if let Some(proposal_state) = Arc::make_mut(&mut self.governance)
                    .proposals
                    .remove(action_id)
                {
                    // Refund deposit to return address's reward account
                    let deposit = proposal_state.procedure.deposit;
                    if deposit.0 > 0 {
                        let return_addr = &proposal_state.procedure.return_addr;
                        if return_addr.len() >= 29 {
                            let key = Self::reward_account_to_hash(return_addr);
                            *Arc::make_mut(&mut self.reward_accounts)
                                .entry(key)
                                .or_insert(Lovelace(0)) += deposit;
                        }
                    }
                    debug!(
                        "Governance proposal expired: {:?} (deposit {} returned)",
                        action_id, deposit.0
                    );
                }
            }
            // Remove all votes for expired proposals
            for id in &expired {
                Arc::make_mut(&mut self.governance)
                    .votes_by_action
                    .remove(id);
            }
            debug!(
                "Expired {} governance proposals at epoch {}",
                expired.len(),
                new_epoch.0
            );
        }

        // Store expired proposal IDs for GetRatifyState query (tag 32).
        // This is set regardless of whether proposals expired (clears stale data).
        Arc::make_mut(&mut self.governance).last_expired = expired;

        // Mark inactive DReps per CIP-1694
        // DReps that haven't voted or updated within drep_activity epochs are marked inactive
        // and excluded from voting power calculations. They remain registered and keep their deposits.
        let drep_activity = self.protocol_params.drep_activity;
        if drep_activity > 0 {
            let mut newly_inactive = 0u64;
            let mut reactivated = 0u64;
            for drep in Arc::make_mut(&mut self.governance).dreps.values_mut() {
                let inactive = new_epoch.0.saturating_sub(drep.last_active_epoch.0) > drep_activity;
                if inactive && drep.active {
                    drep.active = false;
                    newly_inactive += 1;
                } else if !inactive && !drep.active {
                    drep.active = true;
                    reactivated += 1;
                }
            }
            if newly_inactive > 0 || reactivated > 0 {
                debug!(
                    "DRep activity update at epoch {}: {} newly inactive, {} reactivated (threshold: {} epochs)",
                    new_epoch.0,
                    newly_inactive,
                    reactivated,
                    drep_activity
                );
            }
        }

        // Expire committee members that have passed their expiration epoch
        let expired_members: Vec<Hash32> = self
            .governance
            .committee_expiration
            .iter()
            .filter(|(_, exp_epoch)| **exp_epoch <= new_epoch)
            .map(|(hash, _)| *hash)
            .collect();
        if !expired_members.is_empty() {
            for hash in &expired_members {
                Arc::make_mut(&mut self.governance)
                    .committee_hot_keys
                    .remove(hash);
                Arc::make_mut(&mut self.governance)
                    .committee_expiration
                    .remove(hash);
            }
            debug!(
                "Expired {} committee members at epoch {}",
                expired_members.len(),
                new_epoch.0
            );
        }

        // Compute new epoch nonce per Haskell TICKN rule:
        //
        //   TRC (TicknEnv extraEntropy ηc ηph, TicknState _ ηh, newEpoch)
        //   epochNonce'    = ηc ⭒ ηh ⭒ extraEntropy   (uses OLD prevHashNonce)
        //   prevHashNonce' = ηph                         (THEN updates to current labNonce)
        //
        // Critical: use the OLD last_epoch_block_nonce FIRST, then update it.
        // In Haskell ηh = previous ticknStatePrevHashNonce (NOT the just-captured lab).
        let _prev_epoch_nonce = self.epoch_nonce;
        let candidate = self.candidate_nonce;
        let prev_hash_nonce = self.last_epoch_block_nonce; // ηh = OLD value

        debug!(
            epoch = new_epoch.0,
            candidate = %candidate.to_hex(),
            prev_hash_nonce = %prev_hash_nonce.to_hex(),
            block_count = self.epoch_block_count,
            "Epoch nonce inputs"
        );

        // Step 1: Compute new epoch nonce using OLD prevHashNonce (ηh).
        // Uses Haskell's Nonce combine (⭒) with NeutralNonce (ZERO) as identity:
        //   epochNonce = candidate ⭒ prevHashNonce ⭒ extraEntropy
        //   NeutralNonce ⭒ x = x;  x ⭒ NeutralNonce = x
        //   Nonce(a) ⭒ Nonce(b) = Nonce(blake2b_256(a || b))
        // extraEntropy is NeutralNonce on all real networks, so omitted.
        let zero = torsten_primitives::hash::Hash32::ZERO;
        self.epoch_nonce = if candidate == zero && prev_hash_nonce == zero {
            zero
        } else if candidate == zero {
            prev_hash_nonce
        } else if prev_hash_nonce == zero {
            candidate // identity: candidate ⭒ NeutralNonce = candidate
        } else {
            let mut nonce_input = Vec::with_capacity(64);
            nonce_input.extend_from_slice(candidate.as_bytes());
            nonce_input.extend_from_slice(prev_hash_nonce.as_bytes());
            torsten_primitives::hash::blake2b_256(&nonce_input)
        };

        // Step 2: NOW update prevHashNonce to current labNonce for NEXT epoch
        self.last_epoch_block_nonce = self.lab_nonce;

        debug!(
            epoch = new_epoch.0,
            nonce = %self.epoch_nonce.to_hex(),
            "Epoch nonce"
        );

        // evolving_nonce and candidate_nonce carry forward unchanged
        // (they are NOT reset at epoch boundaries)

        // Reset per-epoch accumulators
        self.epoch_fees = Lovelace(0);
        Arc::make_mut(&mut self.epoch_blocks_by_pool).clear();
        self.epoch_block_count = 0;

        self.epoch = new_epoch;
    }

    /// Rebuild stake_distribution.stake_map from the full UTxO set.
    ///
    /// This recomputes per-credential UTxO stake by scanning all UTxOs,
    /// matching Haskell's behavior at epoch boundaries. This corrects any
    /// drift from incremental tracking (e.g., after snapshot load or Mithril import).
    pub fn rebuild_stake_distribution(&mut self) {
        // Pre-size to the current credential count to minimise rehashing.
        let mut new_map: HashMap<Hash32, Lovelace> =
            HashMap::with_capacity(self.stake_distribution.stake_map.len());
        for (_, output) in self.utxo_set.iter() {
            if let Some(cred_hash) = stake_credential_hash(&output.address) {
                *new_map.entry(cred_hash).or_insert(Lovelace(0)) += Lovelace(output.value.coin.0);
            }
        }
        // Also ensure all registered stake credentials have entries (even with 0 stake)
        for cred_hash in self.delegations.keys() {
            new_map.entry(*cred_hash).or_insert(Lovelace(0));
        }
        self.stake_distribution.stake_map = new_map;
    }

    /// Recompute pool_stake for all existing snapshots (mark/set/go).
    ///
    /// After rebuilding stake_distribution from the UTxO set, this updates
    /// each snapshot's pool_stake map using the current (rebuilt) stake
    /// distribution and reward accounts.  Crucially, each snapshot's own
    /// delegation map is preserved — it reflects the delegations that were
    /// active at the time the snapshot epoch boundary was crossed.  Replacing
    /// snapshot delegations with the current map would incorrectly include
    /// delegations that became active AFTER the snapshot epoch, producing
    /// inflated sigma values for historical snapshots (issue #171).
    ///
    /// The zero-stake bug (issue #113) is handled separately by the
    /// `rebuild_stake_distribution` + `recompute_snapshot_pool_stakes` call
    /// in node startup code after the UTxO store is attached.
    pub fn recompute_snapshot_pool_stakes(&mut self) {
        for (name, snapshot) in [
            ("mark", &mut self.snapshots.mark),
            ("set", &mut self.snapshots.set),
            ("go", &mut self.snapshots.go),
        ] {
            if let Some(snap) = snapshot {
                let old_total: u64 = snap
                    .pool_stake
                    .values()
                    .fold(0u64, |acc, s| acc.saturating_add(s.0));
                let mut new_pool_stake: HashMap<torsten_primitives::hash::Hash28, Lovelace> =
                    HashMap::with_capacity(snap.pool_stake.len());
                for (cred_hash, pool_id) in snap.delegations.iter() {
                    let utxo_stake = self
                        .stake_distribution
                        .stake_map
                        .get(cred_hash)
                        .copied()
                        .unwrap_or(Lovelace(0));
                    let reward_balance = self
                        .reward_accounts
                        .get(cred_hash)
                        .copied()
                        .unwrap_or(Lovelace(0));
                    let total_stake = Lovelace(utxo_stake.0.saturating_add(reward_balance.0));
                    *new_pool_stake.entry(*pool_id).or_insert(Lovelace(0)) += total_stake;
                }
                let new_total: u64 = new_pool_stake
                    .values()
                    .fold(0u64, |acc, s| acc.saturating_add(s.0));
                if old_total != new_total {
                    debug!(
                        snapshot = name,
                        epoch = snap.epoch.0,
                        old_total_ada = old_total / 1_000_000,
                        new_total_ada = new_total / 1_000_000,
                        delta_ada = (new_total as i128 - old_total as i128) / 1_000_000,
                        "Snapshot pool_stake recomputed (corrected drift)"
                    );
                }
                snap.pool_stake = new_pool_stake;
            }
        }
    }

    /// Update the evolving nonce with a pre-computed nonce VRF contribution (eta).
    ///
    /// evolving_nonce = blake2b_256(evolving_nonce || eta)
    ///
    /// The `nonce_eta` argument is the era-specific nonce contribution stored in
    /// `BlockHeader::nonce_vrf_output`:
    ///
    /// - Shelley/Allegra/Mary/Alonzo (TPraos): eta = blake2b_256(nonce_vrf_cert.0)
    /// - Babbage/Conway (Praos): eta = blake2b_256("N" || vrf_result.0)
    ///
    /// This function does NOT do any additional hashing of the input — the caller
    /// (serialization) is responsible for computing eta correctly per era.  This
    /// exactly matches Haskell's reupdateChainDepState:
    ///
    ///   eta = vrfNonceValue block
    ///   evolving_nonce' = updateNonce evolving_nonce eta
    ///   where updateNonce n e = hash (n <> e)
    pub(crate) fn update_evolving_nonce(&mut self, nonce_eta: &[u8]) {
        // Combines evolving nonce with a pre-computed 32-byte eta:
        //   evolving' = blake2b_256(evolving || eta)
        //
        // The caller (serialization/multi_era.rs) always provides a pre-computed 32-byte eta:
        //   TPraos (Shelley-Alonzo): eta = blake2b_256(nonce_vrf.0)   — one hash of raw 64-byte VRF
        //   Praos  (Babbage/Conway): eta = blake2b_256("N"||vrf.0)    — one hash of tagged VRF
        //
        // This function does NOT add any extra hashing — the input IS the eta.
        // This matches Haskell's updateNonce: hash(evolving || eta)
        // where eta was already computed as vrfNonceValue in reupdateChainDepState.
        let prev = self.evolving_nonce;
        // ALWAYS hash the input — matching pallas's generate_rolling_nonce exactly.
        // DO NOT use a pass-through for 32-byte inputs — this was verified to produce
        // wrong nonces. The hash step is required for both TPraos and Praos:
        //   TPraos (64-byte raw nonce_vrf.0): eta = blake2b_256(raw) — 1 hash total
        //   Praos  (32-byte nonce_vrf_output): eta = blake2b_256(tagged_hash) — 2nd hash
        let eta_hash = torsten_primitives::hash::blake2b_256(nonce_eta);
        let mut data = Vec::with_capacity(64);
        data.extend_from_slice(self.evolving_nonce.as_bytes());
        data.extend_from_slice(eta_hash.as_bytes());
        self.evolving_nonce = torsten_primitives::hash::blake2b_256(&data);

        let _ = prev; // suppress unused warning in release
    }
}
