apiVersion: v2
name: dugite-node
description: A Helm chart for deploying Dugite, a Rust implementation of the Cardano node
type: application
version: 0.1.0
appVersion: "1.0.3-alpha"
keywords:
  - cardano
  - blockchain
  - relay
  - block-producer
home: https://github.com/michaeljfazio/dugite
sources:
  - https://github.com/michaeljfazio/dugite
maintainers:
  - name: Michael Fazio
