//! Golden tests for N2C query result CBOR encoding.
//!
//! Each test constructs a QueryResult with known synthetic data, encodes it
//! via `encode_query_result`, and compares the output against a binary fixture
//! file in `tests/golden/n2c/`. This validates that our CBOR encoding is
//! deterministic and structurally correct.
//!
//! The fixture files were generated by running these tests with
//! `GOLDEN_UPDATE=1` to write the encoded bytes, then frozen as reference.

use torsten_network::encode_query_result;
use torsten_network::query_handler::{
    DRepSnapshot, GovStateSnapshot, NonMyopicRewardEntry, PoolParamsSnapshot, PoolRewardInfo,
    ProtocolParamsSnapshot, QueryResult, RelaySnapshot, StakePoolSnapshot,
};

/// Strip the MsgResult `[4, ...]` wrapper and HFC `[1, ...]` wrapper,
/// returning just the result payload for structural validation.
fn strip_msg_and_hfc(encoded: &[u8]) -> &[u8] {
    // MsgResult: 82 04 ... = array(2) [4, payload]
    // For BlockQuery results, payload is: 81 <result> = array(1) [result]
    // So header is: 82 04 81 = 3 bytes
    assert_eq!(encoded[0], 0x82, "expected array(2)");
    assert_eq!(encoded[1], 0x04, "expected MsgResult tag 4");
    assert_eq!(encoded[2], 0x81, "expected HFC success array(1)");
    &encoded[3..]
}

/// Helper: decode a minicbor value from bytes and return the decoder
fn decoder(data: &[u8]) -> minicbor::Decoder<'_> {
    minicbor::Decoder::new(data)
}

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

fn fixture_path(name: &str) -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("n2c");
    p.push(name);
    p
}

/// Load or update a fixture file. When GOLDEN_UPDATE=1 is set, writes the
/// encoded bytes to the fixture path so they can be committed.
fn assert_fixture(name: &str, encoded: &[u8]) {
    let path = fixture_path(name);
    if std::env::var("GOLDEN_UPDATE").is_ok() {
        std::fs::write(&path, encoded).expect("failed to write fixture");
    }
    let expected = std::fs::read(&path).unwrap_or_else(|_| {
        panic!(
            "fixture file not found: {:?}. Run with GOLDEN_UPDATE=1 to generate.",
            path
        )
    });
    assert_eq!(
        encoded,
        &expected[..],
        "CBOR mismatch for fixture {name} (len got={}, expected={})",
        encoded.len(),
        expected.len()
    );
}

// ===========================================================================
// Test 1: GetNonMyopicMemberRewards (tag 2)
// ===========================================================================

fn make_non_myopic_rewards() -> QueryResult {
    QueryResult::NonMyopicMemberRewards(vec![
        NonMyopicRewardEntry {
            stake_amount: 1_000_000_000,
            pool_rewards: vec![(vec![0xAA; 28], 50_000), (vec![0xBB; 28], 75_000)],
        },
        NonMyopicRewardEntry {
            stake_amount: 5_000_000_000,
            pool_rewards: vec![(vec![0xCC; 28], 250_000)],
        },
    ])
}

#[test]
fn test_non_myopic_member_rewards_fixture() {
    let result = make_non_myopic_rewards();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_NonMyopicMemberRewards", &encoded);
}

#[test]
fn test_non_myopic_member_rewards_structure() {
    let result = make_non_myopic_rewards();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // Outer map: stake_amount -> pool_rewards_map
    let map_len = dec.map().unwrap().unwrap();
    assert_eq!(map_len, 2, "expected 2 stake amount entries");

    // Entry 1: stake=1_000_000_000
    assert_eq!(dec.u64().unwrap(), 1_000_000_000);
    let inner_len = dec.map().unwrap().unwrap();
    assert_eq!(inner_len, 2, "expected 2 pool rewards for first entry");
    assert_eq!(dec.bytes().unwrap(), &[0xAA; 28]);
    assert_eq!(dec.u64().unwrap(), 50_000);
    assert_eq!(dec.bytes().unwrap(), &[0xBB; 28]);
    assert_eq!(dec.u64().unwrap(), 75_000);

    // Entry 2: stake=5_000_000_000
    assert_eq!(dec.u64().unwrap(), 5_000_000_000);
    let inner_len2 = dec.map().unwrap().unwrap();
    assert_eq!(inner_len2, 1);
    assert_eq!(dec.bytes().unwrap(), &[0xCC; 28]);
    assert_eq!(dec.u64().unwrap(), 250_000);
}

// ===========================================================================
// Test 2: GetStakeDistribution (tag 7)
// ===========================================================================

fn make_stake_distribution() -> QueryResult {
    QueryResult::StakeDistribution(vec![
        StakePoolSnapshot {
            pool_id: vec![0x11; 28],
            stake: 300_000_000,
            vrf_keyhash: vec![0x22; 32],
            total_active_stake: 1_000_000_000,
        },
        StakePoolSnapshot {
            pool_id: vec![0x33; 28],
            stake: 700_000_000,
            vrf_keyhash: vec![0x44; 32],
            total_active_stake: 1_000_000_000,
        },
    ])
}

#[test]
fn test_stake_distribution_fixture() {
    let result = make_stake_distribution();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_StakeDistribution", &encoded);
}

#[test]
fn test_stake_distribution_structure() {
    let result = make_stake_distribution();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // Map<pool_hash(28), IndividualPoolStake>
    let map_len = dec.map().unwrap().unwrap();
    assert_eq!(map_len, 2);

    // Pool 1
    assert_eq!(dec.bytes().unwrap(), &[0x11; 28]);
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 2, "IndividualPoolStake = array(2)");
    // tag(30) rational
    let tag = dec.tag().unwrap();
    assert_eq!(tag.as_u64(), 30, "expected tag(30) for rational");
    let rat_arr = dec.array().unwrap().unwrap();
    assert_eq!(rat_arr, 2);
    let num = dec.u64().unwrap();
    let den = dec.u64().unwrap();
    assert_eq!(num, 300_000_000);
    assert_eq!(den, 1_000_000_000);
    // VRF keyhash
    assert_eq!(dec.bytes().unwrap(), &[0x22; 32]);

    // Pool 2
    assert_eq!(dec.bytes().unwrap(), &[0x33; 28]);
    let arr2 = dec.array().unwrap().unwrap();
    assert_eq!(arr2, 2);
    dec.skip().unwrap(); // skip rational
    assert_eq!(dec.bytes().unwrap(), &[0x44; 32]);
}

// ===========================================================================
// Test 3: GetRewardInfoPools (tag 18)
// ===========================================================================

fn make_reward_info_pools() -> QueryResult {
    QueryResult::RewardInfoPools(vec![PoolRewardInfo {
        pool_id: vec![0xAB; 28],
        stake: 500_000_000_000,
        owner_stake: 50_000_000_000,
        pool_reward: 1_000_000,
        leader_reward: 400_000,
        member_reward: 600_000,
        margin: (3, 100),
        cost: 340_000_000,
    }])
}

#[test]
fn test_reward_info_pools_fixture() {
    let result = make_reward_info_pools();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_RewardInfoPools", &encoded);
}

#[test]
fn test_reward_info_pools_structure() {
    let result = make_reward_info_pools();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // Map<pool_hash, PoolRewardInfo>
    let map_len = dec.map().unwrap().unwrap();
    assert_eq!(map_len, 1);

    assert_eq!(dec.bytes().unwrap(), &[0xAB; 28]);
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 7, "PoolRewardInfo = array(7)");

    assert_eq!(dec.u64().unwrap(), 500_000_000_000, "stake");
    assert_eq!(dec.u64().unwrap(), 50_000_000_000, "owner_stake");
    assert_eq!(dec.u64().unwrap(), 1_000_000, "pool_reward");
    assert_eq!(dec.u64().unwrap(), 400_000, "leader_reward");
    assert_eq!(dec.u64().unwrap(), 600_000, "member_reward");

    // Margin: tag(30)[3, 100]
    let tag = dec.tag().unwrap();
    assert_eq!(tag.as_u64(), 30);
    let rat_arr = dec.array().unwrap().unwrap();
    assert_eq!(rat_arr, 2);
    assert_eq!(dec.u64().unwrap(), 3);
    assert_eq!(dec.u64().unwrap(), 100);

    assert_eq!(dec.u64().unwrap(), 340_000_000, "cost");
}

// ===========================================================================
// Test 4: GetPoolState (tag 19)
// ===========================================================================

fn make_pool_state() -> QueryResult {
    let pool_params = PoolParamsSnapshot {
        pool_id: vec![0xDE; 28],
        vrf_keyhash: vec![0xEF; 32],
        pledge: 1_000_000_000,
        cost: 340_000_000,
        margin_num: 1,
        margin_den: 100,
        reward_account: vec![0xE0; 29],
        owners: vec![vec![0xA1; 28]],
        relays: vec![RelaySnapshot::SingleHostName {
            port: Some(3001),
            dns_name: "relay1.example.com".to_string(),
        }],
        metadata_url: Some("https://example.com/pool.json".to_string()),
        metadata_hash: Some(vec![0xBE; 32]),
    };

    QueryResult::PoolState {
        pool_params: vec![pool_params],
        future_pool_params: vec![],
        retiring: vec![(vec![0xCC; 28], 500)],
        deposits: vec![(vec![0xDE; 28], 500_000_000)],
    }
}

#[test]
fn test_pool_state_fixture() {
    let result = make_pool_state();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_PoolState", &encoded);
}

#[test]
fn test_pool_state_structure() {
    let result = make_pool_state();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // QueryPoolStateResult: array(4)
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 4, "PoolState = array(4)");

    // [0] pool_params map (1 entry)
    let map0 = dec.map().unwrap().unwrap();
    assert_eq!(map0, 1);
    assert_eq!(dec.bytes().unwrap(), &[0xDE; 28]); // pool_id key
                                                   // PoolParams is an array — just skip it for structural check
    dec.skip().unwrap();

    // [1] future_pool_params map (0 entries)
    let map1 = dec.map().unwrap().unwrap();
    assert_eq!(map1, 0);

    // [2] retiring map (1 entry)
    let map2 = dec.map().unwrap().unwrap();
    assert_eq!(map2, 1);
    assert_eq!(dec.bytes().unwrap(), &[0xCC; 28]);
    assert_eq!(dec.u64().unwrap(), 500);

    // [3] deposits map (1 entry)
    let map3 = dec.map().unwrap().unwrap();
    assert_eq!(map3, 1);
    assert_eq!(dec.bytes().unwrap(), &[0xDE; 28]);
    assert_eq!(dec.u64().unwrap(), 500_000_000);
}

// ===========================================================================
// Test 5: GetConstitution (tag 23)
// ===========================================================================

fn make_constitution() -> QueryResult {
    QueryResult::Constitution {
        url: "https://constitution.gov/doc.json".to_string(),
        data_hash: vec![0xFF; 32],
        script_hash: Some(vec![0xDD; 28]),
    }
}

fn make_constitution_no_script() -> QueryResult {
    QueryResult::Constitution {
        url: "https://constitution.gov/doc.json".to_string(),
        data_hash: vec![0xFF; 32],
        script_hash: None,
    }
}

#[test]
fn test_constitution_with_script_fixture() {
    let result = make_constitution();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_Constitution", &encoded);
}

#[test]
fn test_constitution_no_script_fixture() {
    let result = make_constitution_no_script();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_Constitution_NoScript", &encoded);
}

#[test]
fn test_constitution_structure() {
    let result = make_constitution();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // Constitution = array(2) [Anchor, StrictMaybe ScriptHash]
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 2, "Constitution = array(2)");

    // Anchor = array(2) [url, hash]
    let anchor_arr = dec.array().unwrap().unwrap();
    assert_eq!(anchor_arr, 2, "Anchor = array(2)");
    assert_eq!(dec.str().unwrap(), "https://constitution.gov/doc.json");
    assert_eq!(dec.bytes().unwrap(), &[0xFF; 32]);

    // ScriptHash (Just = bytes)
    assert_eq!(dec.bytes().unwrap(), &[0xDD; 28]);
}

#[test]
fn test_constitution_no_script_structure() {
    let result = make_constitution_no_script();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 2);
    let _ = dec.array(); // anchor
    let _ = dec.str(); // url
    let _ = dec.bytes(); // hash
                         // StrictMaybe Nothing = null
    assert!(dec.null().is_ok(), "expected null for Nothing script hash");
}

// ===========================================================================
// Test 6: GetGovState (tag 24)
// ===========================================================================

fn make_gov_state() -> QueryResult {
    QueryResult::GovState(Box::new(GovStateSnapshot {
        proposals: vec![],
        committee: Default::default(),
        constitution_url: "https://gov.example.com".to_string(),
        constitution_hash: vec![0xEE; 32],
        constitution_script: None,
        cur_pparams: Box::new(ProtocolParamsSnapshot::default()),
        prev_pparams: Box::new(ProtocolParamsSnapshot::default()),
        enacted_pparam_update: None,
        enacted_hard_fork: None,
        enacted_committee: None,
        enacted_constitution: None,
        treasury: 14_000_000_000_000_000,
    }))
}

#[test]
fn test_gov_state_fixture() {
    let result = make_gov_state();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_GovState", &encoded);
}

#[test]
fn test_gov_state_structure() {
    let result = make_gov_state();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // ConwayGovState = array(7)
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 7, "GovState = array(7)");

    // [0] Proposals = array(2) [roots, values]
    let prop_arr = dec.array().unwrap().unwrap();
    assert_eq!(prop_arr, 2, "Proposals = array(2)");
    // roots = array(4) of StrictMaybe
    let roots = dec.array().unwrap().unwrap();
    assert_eq!(roots, 4, "4 governance purpose roots");
    // All are Nothing = array(0)
    for _ in 0..4 {
        let nothing = dec.array().unwrap().unwrap();
        assert_eq!(nothing, 0, "StrictMaybe Nothing");
    }
    // values = array(0) (no proposals)
    let vals = dec.array().unwrap().unwrap();
    assert_eq!(vals, 0);

    // [1] Committee = StrictMaybe (empty = Nothing = array(0))
    let comm = dec.array().unwrap().unwrap();
    assert_eq!(comm, 0, "empty committee = Nothing");

    // [2] Constitution = array(2) [Anchor, StrictMaybe ScriptHash]
    let const_arr = dec.array().unwrap().unwrap();
    assert_eq!(const_arr, 2);
    // Anchor
    let anch = dec.array().unwrap().unwrap();
    assert_eq!(anch, 2);
    assert_eq!(dec.str().unwrap(), "https://gov.example.com");
    assert_eq!(dec.bytes().unwrap(), &[0xEE; 32]);
    // No script = null
    assert!(dec.null().is_ok());

    // [3] curPParams — skip (large array(31))
    dec.skip().unwrap();
    // [4] prevPParams — skip
    dec.skip().unwrap();

    // [5] FuturePParams = [0] (NoPParamsUpdate)
    let fut = dec.array().unwrap().unwrap();
    assert_eq!(fut, 1);
    assert_eq!(dec.u32().unwrap(), 0);

    // [6] DRepPulsingState = DRComplete (Rec): array(2) [PulsingSnapshot, RatifyState]
    let pulse = dec.array().unwrap().unwrap();
    assert_eq!(pulse, 2);
    // PulsingSnapshot = array(4): [proposals(array), drepDistr(map), drepState(map), poolDistr(map)]
    let snap = dec.array().unwrap().unwrap();
    assert_eq!(snap, 4);
    // [0] psProposals: empty array (StrictSeq)
    let proposals = dec.array().unwrap().unwrap();
    assert_eq!(proposals, 0);
    // [1-3] empty maps
    for _ in 0..3 {
        let m = dec.map().unwrap().unwrap();
        assert_eq!(m, 0);
    }
    // RatifyState = array(4): [EnactState, enacted, expired, delayed]
    let rat = dec.array().unwrap().unwrap();
    assert_eq!(rat, 4);
    // [0] EnactState = array(7)
    let enact = dec.array().unwrap().unwrap();
    assert_eq!(enact, 7, "EnactState = array(7)");
    // ensCommittee: SNothing = array(0)
    let comm2 = dec.array().unwrap().unwrap();
    assert_eq!(comm2, 0);
    // ensConstitution: array(2) — skip
    dec.skip().unwrap();
    // ensCurPParams: array(31) — skip
    dec.skip().unwrap();
    // ensPrevPParams: array(31) — skip
    dec.skip().unwrap();
    // ensTreasury: Coin
    let _treasury = dec.u64().unwrap();
    // ensWithdrawals: empty map
    let wd = dec.map().unwrap().unwrap();
    assert_eq!(wd, 0);
    // ensPrevGovActionIds: array(4) of StrictMaybe
    let prev_ids = dec.array().unwrap().unwrap();
    assert_eq!(prev_ids, 4);
    for _ in 0..4 {
        let nothing = dec.array().unwrap().unwrap();
        assert_eq!(nothing, 0);
    }
    // [1] rsEnacted: array(0) — empty Seq
    let enacted = dec.array().unwrap().unwrap();
    assert_eq!(enacted, 0);
    // [2] rsExpired: tag(258) + array(0) — empty Set
    let tag258 = dec.tag().unwrap();
    assert_eq!(tag258.as_u64(), 258);
    let expired = dec.array().unwrap().unwrap();
    assert_eq!(expired, 0);
    // [3] rsDelayed = false
    assert!(!dec.bool().unwrap());
}

// ===========================================================================
// Test 7: GetDRepState (tag 25)
// ===========================================================================

fn make_drep_state() -> QueryResult {
    QueryResult::DRepState(vec![DRepSnapshot {
        credential_hash: vec![0xAA; 28],
        credential_type: 0, // KeyHash
        deposit: 500_000_000,
        anchor_url: Some("https://drep.example.com/info.json".to_string()),
        anchor_hash: Some(vec![0xBB; 32]),
        expiry_epoch: 100,
        delegator_hashes: vec![vec![0xC1; 28], vec![0xC2; 28]],
    }])
}

#[test]
fn test_drep_state_fixture() {
    let result = make_drep_state();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_DRepState", &encoded);
}

#[test]
fn test_drep_state_structure() {
    let result = make_drep_state();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // Map<Credential, DRepState>
    let map_len = dec.map().unwrap().unwrap();
    assert_eq!(map_len, 1);

    // Key: Credential [type, hash]
    let cred_arr = dec.array().unwrap().unwrap();
    assert_eq!(cred_arr, 2, "Credential = array(2)");
    assert_eq!(dec.u8().unwrap(), 0, "KeyHashObj");
    assert_eq!(dec.bytes().unwrap(), &[0xAA; 28]);

    // Value: DRepState array(4)
    let state_arr = dec.array().unwrap().unwrap();
    assert_eq!(state_arr, 4, "DRepState = array(4)");

    // [0] expiry epoch
    assert_eq!(dec.u64().unwrap(), 100);

    // [1] anchor (SJust)
    let anchor_just = dec.array().unwrap().unwrap();
    assert_eq!(anchor_just, 1, "SJust");
    let anchor = dec.array().unwrap().unwrap();
    assert_eq!(anchor, 2, "Anchor = array(2)");
    assert_eq!(dec.str().unwrap(), "https://drep.example.com/info.json");
    assert_eq!(dec.bytes().unwrap(), &[0xBB; 32]);

    // [2] deposit
    assert_eq!(dec.u64().unwrap(), 500_000_000);

    // [3] delegators: tag(258) set
    let tag = dec.tag().unwrap();
    assert_eq!(tag.as_u64(), 258, "set tag");
    let deleg_arr = dec.array().unwrap().unwrap();
    assert_eq!(deleg_arr, 2, "2 delegators");
    // Delegators are Credential [0, hash] — sorted
    for _ in 0..2 {
        let c = dec.array().unwrap().unwrap();
        assert_eq!(c, 2);
        assert_eq!(dec.u8().unwrap(), 0);
        let _ = dec.bytes().unwrap();
    }
}

// ===========================================================================
// Test 8: GetStakeDistribution2 (tag 37) = PoolDistr2
// ===========================================================================

fn make_stake_distribution2() -> QueryResult {
    QueryResult::PoolDistr2 {
        pools: vec![
            StakePoolSnapshot {
                pool_id: vec![0x55; 28],
                stake: 400_000_000,
                vrf_keyhash: vec![0x66; 32],
                total_active_stake: 1_000_000_000,
            },
            StakePoolSnapshot {
                pool_id: vec![0x77; 28],
                stake: 600_000_000,
                vrf_keyhash: vec![0x88; 32],
                total_active_stake: 1_000_000_000,
            },
        ],
        total_active_stake: 1_000_000_000,
    }
}

#[test]
fn test_stake_distribution2_fixture() {
    let result = make_stake_distribution2();
    let encoded = encode_query_result(&result);
    assert_fixture("Result_Conway_StakeDistribution2", &encoded);
}

#[test]
fn test_stake_distribution2_structure() {
    let result = make_stake_distribution2();
    let encoded = encode_query_result(&result);
    let payload = strip_msg_and_hfc(&encoded);
    let mut dec = decoder(payload);

    // SL.PoolDistr: array(2) [pool_map, total_active_stake]
    let arr = dec.array().unwrap().unwrap();
    assert_eq!(arr, 2, "PoolDistr2 = array(2)");

    // pool_map
    let map_len = dec.map().unwrap().unwrap();
    assert_eq!(map_len, 2);

    // Pool 1
    assert_eq!(dec.bytes().unwrap(), &[0x55; 28]);
    let pool_arr = dec.array().unwrap().unwrap();
    assert_eq!(pool_arr, 3, "IndividualPoolStake = array(3)");
    // rational
    let tag = dec.tag().unwrap();
    assert_eq!(tag.as_u64(), 30);
    let rat = dec.array().unwrap().unwrap();
    assert_eq!(rat, 2);
    assert_eq!(dec.u64().unwrap(), 400_000_000);
    assert_eq!(dec.u64().unwrap(), 1_000_000_000);
    // compact lovelace
    assert_eq!(dec.u64().unwrap(), 400_000_000);
    // VRF hash
    assert_eq!(dec.bytes().unwrap(), &[0x66; 32]);

    // Pool 2
    assert_eq!(dec.bytes().unwrap(), &[0x77; 28]);
    let pool_arr2 = dec.array().unwrap().unwrap();
    assert_eq!(pool_arr2, 3);
    dec.skip().unwrap(); // rational
    assert_eq!(dec.u64().unwrap(), 600_000_000);
    assert_eq!(dec.bytes().unwrap(), &[0x88; 32]);

    // total_active_stake
    assert_eq!(dec.u64().unwrap(), 1_000_000_000);
}
