apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dugite-node.fullname" . }}-config
  labels:
    {{- include "dugite-node.labels" . | nindent 4 }}
data:
  topology.json: |
    {
      "bootstrapPeers": {{ .Values.topology.bootstrapPeers | toJson }},
      "localRoots": [
        {{- range $i, $root := .Values.topology.localRoots }}
        {{- if $i }},{{ end }}
        {
          "accessPoints": {{ $root.accessPoints | toJson }},
          "advertise": {{ $root.advertise | default false }},
          "trustable": {{ $root.trustable | default false }},
          "valency": {{ $root.valency | default 1 }}
        }
        {{- end }}
      ],
      "publicRoots": {{ .Values.topology.publicRoots | toJson }},
      "useLedgerAfterSlot": {{ .Values.topology.useLedgerAfterSlot | int64 }}
    }
