{{- if and (eq .Values.role "producer") (not .Values.producer.existingSecret) }}
{{- if or .Values.producer.kesKey .Values.producer.vrfKey .Values.producer.operationalCertificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "torsten-node.fullname" . }}-producer-keys
  labels:
    {{- include "torsten-node.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.producer.kesKey }}
  kes.skey: {{ .Values.producer.kesKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.producer.vrfKey }}
  vrf.skey: {{ .Values.producer.vrfKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.producer.operationalCertificate }}
  node.cert: {{ .Values.producer.operationalCertificate | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
