use anyhow::{Context, Result};
use std::path::Path;
use torsten_primitives::block::{Block, BlockHeader, OperationalCert, ProtocolVersion, VrfOutput};
use torsten_primitives::era::Era;
use torsten_primitives::hash::{blake2b_256, Hash28, Hash32};
use torsten_primitives::time::{BlockNo, SlotNo};
use torsten_primitives::transaction::Transaction;
use tracing::debug;

/// Block producer credentials loaded from disk
pub struct BlockProducerCredentials {
    /// VRF secret key (32 bytes)
    pub vrf_skey: [u8; 32],
    /// VRF verification key (32 bytes)
    pub vrf_vkey: [u8; 32],
    /// Cold verification key (extracted from opcert)
    pub cold_vkey: Vec<u8>,
    /// KES secret key bytes (Sum6Kes format, 612 bytes)
    pub kes_skey: Vec<u8>,
    /// KES verification key (hot key from opcert)
    pub kes_vkey: Vec<u8>,
    /// Operational certificate sequence number
    pub opcert_sequence: u64,
    /// KES period from the operational certificate
    pub opcert_kes_period: u64,
    /// Operational certificate cold key signature
    pub opcert_sigma: Vec<u8>,
    /// Pool ID (hash of cold verification key)
    pub pool_id: Hash28,
}

impl BlockProducerCredentials {
    /// Load block producer credentials from VRF key, KES key, and operational certificate.
    ///
    /// The cold verification key is extracted from the opcert (which contains it
    /// as a second CBOR element), matching cardano-node behavior. The cold signing
    /// key is NOT needed at runtime.
    pub fn load(vrf_skey_path: &Path, kes_skey_path: &Path, opcert_path: &Path) -> Result<Self> {
        // Load VRF signing key
        let vrf_content = std::fs::read_to_string(vrf_skey_path)
            .with_context(|| format!("Failed to read VRF skey: {}", vrf_skey_path.display()))?;
        let vrf_env: serde_json::Value = serde_json::from_str(&vrf_content)?;
        let vrf_cbor_hex = vrf_env["cborHex"]
            .as_str()
            .ok_or_else(|| anyhow::anyhow!("Missing cborHex in VRF skey file"))?;
        let vrf_cbor = hex::decode(vrf_cbor_hex)?;
        let vrf_key_bytes = unwrap_cbor(&vrf_cbor);
        // cardano-node generates 64-byte VRF secret key files: the first 32 bytes are
        // the secret seed (scalar) and the last 32 bytes are the public key.  Both 32-byte
        // (seed-only) and 64-byte (expanded) formats are accepted for compatibility with
        // keys generated by any version of cardano-cli.
        let mut vrf_skey = [0u8; 32];
        match vrf_key_bytes.len() {
            32 => vrf_skey.copy_from_slice(vrf_key_bytes),
            64 => vrf_skey.copy_from_slice(&vrf_key_bytes[..32]),
            n => anyhow::bail!(
                "VRF secret key must be 32 or 64 bytes, got {n}; \
                 expected either a 32-byte seed or a 64-byte expanded key \
                 as generated by cardano-cli"
            ),
        }

        // Derive VRF public key from secret key
        let vrf_keypair = torsten_crypto::vrf::generate_vrf_keypair_from_secret(&vrf_skey);
        let vrf_vkey = vrf_keypair.public_key;

        // Load KES signing key
        let kes_content = std::fs::read_to_string(kes_skey_path)
            .with_context(|| format!("Failed to read KES skey: {}", kes_skey_path.display()))?;
        let kes_env: serde_json::Value = serde_json::from_str(&kes_content)?;
        let kes_cbor_hex = kes_env["cborHex"]
            .as_str()
            .ok_or_else(|| anyhow::anyhow!("Missing cborHex in KES skey file"))?;
        let kes_cbor = hex::decode(kes_cbor_hex)?;
        let raw_kes_bytes = unwrap_cbor(&kes_cbor);

        // cardano-cli / cardano-node text envelope files store only the raw
        // 608-byte key material (Sum6Kes::SIZE) without the 4-byte period
        // counter that pallas-crypto appends at runtime.  When we see exactly
        // 608 bytes we initialise the period counter to zero, which is correct
        // because the key has not been evolved since it was serialised to disk.
        // The forge path will evolve it forward to the correct period via
        // `kes_evolve_to_period` before signing.
        //
        // If the file already contains 612 bytes (e.g. a key file written by a
        // previous Torsten session that persisted the buffer) we accept it as-is.
        let kes_key_bytes = match raw_kes_bytes.len() {
            torsten_crypto::kes::KES_SECRET_KEY_SIZE => {
                // Text-envelope format: 608 bytes of key material, no period counter.
                // Append period 0 ([0,0,0,0]) so the buffer satisfies pallas's
                // 612-byte invariant.
                let mut buf = Vec::with_capacity(torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE);
                buf.extend_from_slice(raw_kes_bytes);
                buf.extend_from_slice(&[0u8; 4]);
                buf
            }
            torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE => {
                // Already has the period counter (written by Torsten itself).
                raw_kes_bytes.to_vec()
            }
            n => anyhow::bail!(
                "KES secret key must be {} bytes (raw key material) or {} bytes \
                 (key material + period counter), got {n}. \
                 Expected a key file generated by cardano-cli or cardano-node.",
                torsten_crypto::kes::KES_SECRET_KEY_SIZE,
                torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE,
            ),
        };

        // Load operational certificate
        // Opcert CBOR format: ([kes_vkey, sequence, kes_period, sigma], cold_vkey)
        let opcert_content = std::fs::read_to_string(opcert_path)
            .with_context(|| format!("Failed to read opcert: {}", opcert_path.display()))?;
        let opcert_env: serde_json::Value = serde_json::from_str(&opcert_content)?;
        let opcert_cbor_hex = opcert_env["cborHex"]
            .as_str()
            .ok_or_else(|| anyhow::anyhow!("Missing cborHex in opcert file"))?;
        let opcert_cbor = hex::decode(opcert_cbor_hex)?;

        let mut decoder = minicbor::Decoder::new(&opcert_cbor);
        // Opcert CBOR from cardano-cli: array(2) [ array(4)[kes_vkey, seq, kes_period, sigma], cold_vkey ]
        // The outer array wraps the OCert (itself array(4)) and the cold verification key.
        let outer_len = decoder.array()?;
        let (kes_vkey_bytes, opcert_sequence, opcert_kes_period, opcert_sigma, cold_vkey) =
            if outer_len == Some(2) {
                // Standard cardano-cli format: array(2)[array(4)[...], cold_vkey]
                let inner_len = decoder.array()?;
                if inner_len != Some(4) {
                    anyhow::bail!("Expected inner OCert array(4), got array({:?})", inner_len,);
                }
                let kes_vkey = decoder.bytes()?.to_vec();
                let seq = decoder.u64()?;
                let kes_period = decoder.u64()?;
                let sigma = decoder.bytes()?.to_vec();
                let cold = decoder.bytes()?.to_vec();
                (kes_vkey, seq, kes_period, sigma, cold)
            } else {
                // Legacy flat format: array(4 or 5) [kes_vkey, seq, kes_period, sigma, ?cold_vkey]
                let kes_vkey = decoder.bytes()?.to_vec();
                let seq = decoder.u64()?;
                let kes_period = decoder.u64()?;
                let sigma = decoder.bytes()?.to_vec();
                let cold = if outer_len == Some(5) {
                    decoder.bytes()?.to_vec()
                } else {
                    // No cold_vkey in opcert; load from cold.vkey in same directory
                    let opcert_dir = opcert_path.parent().unwrap_or(Path::new("."));
                    let cold_vkey_path = opcert_dir.join("cold.vkey");
                    let cold_content =
                        std::fs::read_to_string(&cold_vkey_path).with_context(|| {
                            format!(
                                "Opcert has no cold_vkey; failed to load {}",
                                cold_vkey_path.display()
                            )
                        })?;
                    let cold_env: serde_json::Value = serde_json::from_str(&cold_content)?;
                    let cold_cbor_hex = cold_env["cborHex"]
                        .as_str()
                        .ok_or_else(|| anyhow::anyhow!("Missing cborHex in cold.vkey"))?;
                    let cold_cbor = hex::decode(cold_cbor_hex)?;
                    unwrap_cbor(&cold_cbor).to_vec()
                };
                (kes_vkey, seq, kes_period, sigma, cold)
            };

        if cold_vkey.len() != 32 {
            anyhow::bail!(
                "Cold verification key must be 32 bytes, got {}",
                cold_vkey.len(),
            );
        }

        // Pool ID = blake2b-224 of the cold verification key
        let pool_id = torsten_primitives::hash::blake2b_224(&cold_vkey);

        Ok(BlockProducerCredentials {
            vrf_skey,
            vrf_vkey,
            cold_vkey,
            kes_skey: kes_key_bytes,
            kes_vkey: kes_vkey_bytes,
            opcert_sequence,
            opcert_kes_period,
            opcert_sigma,
            pool_id,
        })
    }
}

/// Build CBOR byte string representation of `data`.
///
/// Inverse of `unwrap_cbor`: wraps `data` in the smallest valid CBOR byte
/// string header.  Used by tests to construct synthetic key envelopes without
/// pulling in a full CBOR encoder as a dev-dependency.
#[cfg(test)]
fn wrap_cbor(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len() + 3);
    match data.len() {
        0..=23 => out.push(0x40 | data.len() as u8),
        24..=255 => {
            out.push(0x58);
            out.push(data.len() as u8);
        }
        256..=65535 => {
            out.push(0x59);
            out.extend_from_slice(&(data.len() as u16).to_be_bytes());
        }
        n => {
            out.push(0x5a);
            out.extend_from_slice(&(n as u32).to_be_bytes());
        }
    }
    out.extend_from_slice(data);
    out
}

/// Strip CBOR byte string wrapper.
/// Handles major type 2 (byte string) in all length forms:
///   - 0x40-0x57: short form (length in low 5 bits, 1 byte header)
///   - 0x58: 1-byte length follows (2 byte header)
///   - 0x59: 2-byte length follows (3 byte header)
///   - 0x5a: 4-byte length follows (5 byte header)
fn unwrap_cbor(data: &[u8]) -> &[u8] {
    if data.is_empty() {
        return data;
    }
    match data[0] {
        0x58 if data.len() > 2 => &data[2..],
        0x59 if data.len() > 3 => &data[3..],
        0x5a if data.len() > 5 => &data[5..],
        b if (b & 0xe0) == 0x40 && data.len() > 1 => &data[1..],
        _ => data,
    }
}

/// Configuration for the block producer
pub struct BlockProducerConfig {
    /// Protocol version to stamp on forged blocks
    pub protocol_version: ProtocolVersion,
    /// Maximum block body size in bytes
    pub _max_block_body_size: u64,
    /// Maximum number of transactions per block
    pub _max_txs_per_block: usize,
    /// Current era for the forged block
    pub era: Era,
    /// Slots per KES period (from genesis config)
    pub slots_per_kes_period: u64,
}

impl Default for BlockProducerConfig {
    fn default() -> Self {
        BlockProducerConfig {
            protocol_version: ProtocolVersion { major: 9, minor: 0 },
            _max_block_body_size: 90112,
            _max_txs_per_block: 500,
            era: Era::Conway,
            slots_per_kes_period: 129600,
        }
    }
}

/// Forge a new block from mempool transactions.
///
/// Returns the constructed block and its CBOR encoding.
/// The block header is signed with the KES secret key at the appropriate period.
pub fn forge_block(
    creds: &BlockProducerCredentials,
    config: &BlockProducerConfig,
    slot: SlotNo,
    block_number: BlockNo,
    prev_hash: Hash32,
    epoch_nonce: &Hash32,
    transactions: Vec<Transaction>,
) -> Result<(Block, Vec<u8>)> {
    // Generate VRF proof for this slot
    let vrf_seed = torsten_consensus::slot_leader::vrf_input(epoch_nonce, slot);
    let (vrf_proof, vrf_output) =
        torsten_crypto::vrf::generate_vrf_proof(&creds.vrf_skey, &vrf_seed)
            .map_err(|e| anyhow::anyhow!("VRF proof generation failed: {e}"))?;

    // Encode transaction bodies to compute body hash and size
    let body_hash = torsten_serialization::compute_block_body_hash(&transactions);
    let body_size = compute_body_size(&transactions);

    // Compute the nonce VRF contribution for Babbage/Conway (Praos era).
    // nonce_vrf_output = blake2b_256("N" || vrf_output.0)
    // This matches pallas's HeaderBody::nonce_vrf_output() derivation and
    // Haskell's vrfNonceValue for the Praos era.  When this forged block is
    // applied to the ledger, update_evolving_nonce() will incorporate it into
    // the evolving nonce without any additional hashing.
    let nonce_vrf_output = {
        let mut tagged = Vec::with_capacity(1 + vrf_output.len());
        tagged.push(b'N');
        tagged.extend_from_slice(&vrf_output);
        blake2b_256(&tagged).to_vec()
    };

    // Build the block header
    let header = BlockHeader {
        header_hash: Hash32::ZERO, // Will be set after encoding
        prev_hash,
        issuer_vkey: creds.cold_vkey.clone(),
        vrf_vkey: creds.vrf_vkey.to_vec(),
        vrf_result: VrfOutput {
            output: vrf_output.to_vec(),
            proof: vrf_proof.to_vec(),
        },
        block_number,
        slot,
        epoch_nonce: *epoch_nonce,
        body_size,
        body_hash,
        operational_cert: OperationalCert {
            hot_vkey: creds.kes_vkey.clone(),
            sequence_number: creds.opcert_sequence,
            kes_period: creds.opcert_kes_period,
            sigma: creds.opcert_sigma.clone(),
        },
        protocol_version: config.protocol_version,
        kes_signature: vec![], // Set after signing below
        nonce_vrf_output,
    };

    // Encode the header body for KES signing
    let header_body_cbor = torsten_serialization::encode_block_header_body(&header);

    // KES signing: evolve key to the correct period and sign the header body
    let current_slot_kes_period = slot.0 / config.slots_per_kes_period;
    let kes_period_offset = current_slot_kes_period.saturating_sub(creds.opcert_kes_period);

    // Validate KES period offset is within bounds (Sum6Kes supports 62 evolutions)
    const MAX_KES_EVOLUTIONS: u64 = 62;
    // Sum6Kes supports periods 0..=61 (62 evolutions). Period 62 is expired.
    // Using >= to match consensus validation at praos.rs which also uses >=.
    if kes_period_offset >= MAX_KES_EVOLUTIONS {
        anyhow::bail!(
            "KES key expired: current period {} - opcert period {} = offset {} > max {}. \
             Rotate your KES key and issue a new operational certificate.",
            current_slot_kes_period,
            creds.opcert_kes_period,
            kes_period_offset,
            MAX_KES_EVOLUTIONS
        );
    }

    let kes_signature = if !creds.kes_skey.is_empty() {
        let evolved_kes =
            torsten_crypto::kes::kes_evolve_to_period(&creds.kes_skey, kes_period_offset as u32)
                .map_err(|e| anyhow::anyhow!("KES key evolution failed: {e}"))?;

        let (sig_bytes, period) =
            torsten_crypto::kes::kes_sign_bytes(&evolved_kes, &header_body_cbor)
                .map_err(|e| anyhow::anyhow!("KES signing failed: {e}"))?;

        debug!(
            kes_period = period,
            slot_kes_period = current_slot_kes_period,
            opcert_kes_period = creds.opcert_kes_period,
            "KES signature produced"
        );
        sig_bytes
    } else {
        anyhow::bail!("Cannot forge block: KES secret key is empty");
    };

    // Compute the canonical block header hash from the FULL header CBOR
    // (header_body + KES signature), NOT just the header body.
    //
    // The Cardano block hash is blake2b_256 of the serialized Header struct,
    // which is a 2-element CBOR array: [header_body_cbor, kes_signature].
    // Using header_body_cbor alone produces a wrong hash that peers cannot
    // verify, causing block rejection and wrong prev_hash in subsequent blocks.
    let full_header_cbor = torsten_serialization::encode_block_header(&header, &kes_signature);
    let header_hash = blake2b_256(&full_header_cbor);

    // Build the final block with correct header hash
    let mut block = Block {
        header,
        transactions,
        era: config.era,
        raw_cbor: None,
    };
    block.header.header_hash = header_hash;
    block.header.kes_signature = kes_signature.clone();

    // Encode the full block
    let block_cbor = torsten_serialization::encode_block(&block, &kes_signature);
    block.raw_cbor = Some(block_cbor.clone());

    debug!(
        slot = slot.0,
        block_number = block_number.0,
        tx_count = block.transactions.len(),
        body_size = body_size,
        header_hash = %header_hash,
        "Block forged"
    );

    Ok((block, block_cbor))
}

/// Compute approximate body size from transactions
/// Compute the block body size matching Haskell's `bbodySz` field.
///
/// The body size is the total byte count of the 4 segregated components:
///   CBOR_array(tx_bodies) + CBOR_array(witness_sets) + CBOR_map(aux_data) + CBOR_array(invalid_indices)
///
/// This must match the structure used by `compute_block_body_hash` and `encode_block`.
fn compute_body_size(transactions: &[Transaction]) -> u64 {
    use torsten_serialization::cbor::{encode_array_header, encode_map_header, encode_uint};
    use torsten_serialization::encode::{
        encode_auxiliary_data, encode_transaction_body, encode_witness_set,
    };

    // 1. tx_bodies array
    let mut bodies_len = encode_array_header(transactions.len()).len();
    for tx in transactions {
        bodies_len += encode_transaction_body(&tx.body).len();
    }

    // 2. witness_sets array
    let mut wits_len = encode_array_header(transactions.len()).len();
    for tx in transactions {
        wits_len += encode_witness_set(&tx.witness_set).len();
    }

    // 3. aux_data map
    let aux_entries: Vec<_> = transactions
        .iter()
        .enumerate()
        .filter_map(|(i, tx)| tx.auxiliary_data.as_ref().map(|aux| (i, aux)))
        .collect();
    let mut aux_len = encode_map_header(aux_entries.len()).len();
    for (idx, aux) in &aux_entries {
        aux_len += encode_uint(*idx as u64).len();
        aux_len += encode_auxiliary_data(aux).len();
    }

    // 4. invalid_tx_indices array
    let invalid_indices: Vec<_> = transactions
        .iter()
        .enumerate()
        .filter(|(_, tx)| !tx.is_valid)
        .map(|(i, _)| i)
        .collect();
    let mut invalid_len = encode_array_header(invalid_indices.len()).len();
    for idx in &invalid_indices {
        invalid_len += encode_uint(*idx as u64).len();
    }

    (bodies_len + wits_len + aux_len + invalid_len) as u64
}

/// Check if we are the slot leader for a given slot.
///
/// Uses exact rational arithmetic for both sigma (pool_stake/total_stake)
/// and f (f_num/f_den) to avoid f64 precision loss at decision boundaries.
pub fn check_slot_leadership(
    creds: &BlockProducerCredentials,
    slot: SlotNo,
    epoch_nonce: &Hash32,
    pool_stake: u64,
    total_active_stake: u64,
    active_slot_coeff_rational: (u64, u64),
) -> bool {
    if total_active_stake == 0 || pool_stake == 0 {
        return false;
    }
    let vrf_seed = torsten_consensus::slot_leader::vrf_input(epoch_nonce, slot);
    let (f_num, f_den) = active_slot_coeff_rational;
    match torsten_crypto::vrf::generate_vrf_proof(&creds.vrf_skey, &vrf_seed) {
        Ok((_proof, output)) => torsten_consensus::slot_leader::is_slot_leader_rational(
            &output,
            pool_stake,
            total_active_stake,
            f_num,
            f_den,
        ),
        Err(e) => {
            debug!("VRF proof failed for slot {}: {e}", slot.0);
            false
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use torsten_primitives::transaction::TransactionBody;

    fn make_test_credentials() -> BlockProducerCredentials {
        let vrf_kp = torsten_crypto::vrf::generate_vrf_keypair();
        let cold_sk = torsten_crypto::keys::PaymentSigningKey::generate();
        let cold_vk = cold_sk.verification_key();
        let cold_vkey = cold_vk.to_bytes().to_vec();

        // Generate a KES key pair for testing
        let seed = [42u8; 32];
        let (kes_sk, kes_pk) = torsten_crypto::kes::kes_keygen(&seed).unwrap();

        BlockProducerCredentials {
            vrf_skey: *vrf_kp.secret_key(),
            vrf_vkey: vrf_kp.public_key,
            cold_vkey: cold_vkey.clone(),
            kes_skey: kes_sk,
            kes_vkey: kes_pk.to_vec(),
            opcert_sequence: 0,
            opcert_kes_period: 0,
            opcert_sigma: vec![0u8; 64],
            pool_id: torsten_primitives::hash::blake2b_224(&cold_vkey),
        }
    }

    #[test]
    fn test_forge_empty_block() {
        let creds = make_test_credentials();
        let config = BlockProducerConfig::default();
        let epoch_nonce = Hash32::from_bytes([42u8; 32]);

        let (block, cbor) = forge_block(
            &creds,
            &config,
            SlotNo(1000),
            BlockNo(100),
            Hash32::ZERO,
            &epoch_nonce,
            vec![],
        )
        .expect("forge_block should succeed");

        assert_eq!(block.transactions.len(), 0);
        assert_eq!(block.header.slot, SlotNo(1000));
        assert_eq!(block.header.block_number, BlockNo(100));
        assert_ne!(block.header.header_hash, Hash32::ZERO);
        assert!(!cbor.is_empty());
    }

    #[test]
    fn test_forge_block_with_transactions() {
        let creds = make_test_credentials();
        let config = BlockProducerConfig::default();
        let epoch_nonce = Hash32::from_bytes([42u8; 32]);

        let tx = Transaction {
            hash: Hash32::ZERO,
            body: TransactionBody {
                inputs: vec![torsten_primitives::transaction::TransactionInput {
                    transaction_id: Hash32::ZERO,
                    index: 0,
                }],
                outputs: vec![torsten_primitives::transaction::TransactionOutput {
                    address: torsten_primitives::address::Address::Enterprise(
                        torsten_primitives::address::EnterpriseAddress {
                            network: torsten_primitives::network::NetworkId::Mainnet,
                            payment: torsten_primitives::credentials::Credential::VerificationKey(
                                Hash28::from_bytes([0u8; 28]),
                            ),
                        },
                    ),
                    value: torsten_primitives::value::Value::lovelace(1_000_000),
                    datum: torsten_primitives::transaction::OutputDatum::None,
                    script_ref: None,
                    is_legacy: false,
                    raw_cbor: None,
                }],
                fee: torsten_primitives::value::Lovelace(200_000),
                ttl: None,
                certificates: vec![],
                withdrawals: BTreeMap::new(),
                auxiliary_data_hash: None,
                validity_interval_start: None,
                mint: BTreeMap::new(),
                script_data_hash: None,
                collateral: vec![],
                required_signers: vec![],
                network_id: None,
                collateral_return: None,
                total_collateral: None,
                reference_inputs: vec![],
                update: None,
                voting_procedures: BTreeMap::new(),
                proposal_procedures: vec![],
                treasury_value: None,
                donation: None,
            },
            witness_set: torsten_primitives::transaction::TransactionWitnessSet {
                vkey_witnesses: vec![],
                native_scripts: vec![],
                bootstrap_witnesses: vec![],
                plutus_v1_scripts: vec![],
                plutus_v2_scripts: vec![],
                plutus_v3_scripts: vec![],
                plutus_data: vec![],
                redeemers: vec![],
                raw_redeemers_cbor: None,
                raw_plutus_data_cbor: None,
                pallas_script_data_hash: None,
            },
            is_valid: true,
            auxiliary_data: None,
            raw_cbor: None,
        };

        let (block, _cbor) = forge_block(
            &creds,
            &config,
            SlotNo(2000),
            BlockNo(200),
            Hash32::ZERO,
            &epoch_nonce,
            vec![tx],
        )
        .expect("forge_block should succeed");

        assert_eq!(block.transactions.len(), 1);
        assert!(block.header.body_size > 0);
    }

    #[test]
    fn test_check_slot_leadership() {
        let creds = make_test_credentials();
        let epoch_nonce = Hash32::from_bytes([42u8; 32]);

        // With 100% stake (pool=1000, total=1000), should be leader for some slots
        // f = 1/20 = 0.05
        let mut leader_count = 0;
        for i in 0..100 {
            if check_slot_leadership(&creds, SlotNo(i), &epoch_nonce, 1000, 1000, (1, 20)) {
                leader_count += 1;
            }
        }

        // With f=0.05 and 100% stake, expect ~5 leader slots out of 100
        assert!(leader_count > 0, "Should win some slots with 100% stake");
        assert!(
            leader_count < 50,
            "Should not win too many slots with f=0.05"
        );
    }

    #[test]
    fn test_check_slot_leadership_zero_stake() {
        let creds = make_test_credentials();
        let epoch_nonce = Hash32::from_bytes([42u8; 32]);

        for i in 0..100 {
            assert!(
                !check_slot_leadership(&creds, SlotNo(i), &epoch_nonce, 0, 1000, (1, 20)),
                "Zero stake should never be leader"
            );
        }
    }

    // ─── VRF key loading tests ────────────────────────────────────────────────

    /// Build a minimal JSON text-envelope with cborHex set to the CBOR encoding
    /// of `raw_key_bytes`.  This is the format produced by cardano-cli.
    fn make_vrf_skey_json(raw_key_bytes: &[u8]) -> (tempfile::NamedTempFile, String) {
        use std::io::Write;
        let cbor = wrap_cbor(raw_key_bytes);
        let cbor_hex = hex::encode(&cbor);
        let json = format!(
            r#"{{"type":"VrfSigningKey_PraosVRF","description":"VRF Signing Key","cborHex":"{cbor_hex}"}}"#
        );
        let mut f = tempfile::NamedTempFile::new().expect("tempfile");
        f.write_all(json.as_bytes()).expect("write");
        (f, cbor_hex)
    }

    /// Build a minimal KES skey JSON envelope containing `raw_key_bytes`.
    fn make_kes_skey_json(raw_key_bytes: &[u8]) -> tempfile::NamedTempFile {
        use std::io::Write;
        let cbor = wrap_cbor(raw_key_bytes);
        let cbor_hex = hex::encode(&cbor);
        let json = format!(
            r#"{{"type":"KesSigningKey_ed25519_kes_2^6","description":"KES Signing Key","cborHex":"{cbor_hex}"}}"#
        );
        let mut f = tempfile::NamedTempFile::new().expect("tempfile");
        f.write_all(json.as_bytes()).expect("write");
        f
    }

    /// Build a minimal opcert JSON envelope in the standard cardano-cli format:
    /// array(2) [ array(4)[kes_vkey(32), seq(u64), kes_period(u64), sigma(64)], cold_vkey(32) ]
    fn make_opcert_json(kes_vkey: &[u8; 32], cold_vkey: &[u8; 32]) -> tempfile::NamedTempFile {
        use std::io::Write;
        // Encode outer array(2) [ array(4)[...], cold_vkey_bstr ]
        // Header bytes: 0x82=array(2), 0x84=array(4), 0x58 0xNN=bstr(NN bytes), 0x00=uint(0)
        let mut cbor = vec![
            0x82u8, // array(2)
            0x84u8, // array(4)
            0x58, 32, // bstr(32) — kes_vkey
        ];
        cbor.extend_from_slice(kes_vkey);
        cbor.extend_from_slice(&[
            0x00, // seq = 0
            0x00, // kes_period = 0
            0x58, 64, // bstr(64) — sigma
        ]);
        cbor.extend_from_slice(&[0u8; 64]);
        cbor.extend_from_slice(&[0x58, 32]); // bstr(32) — cold_vkey
        cbor.extend_from_slice(cold_vkey);

        let cbor_hex = hex::encode(&cbor);
        let json = format!(
            r#"{{"type":"NodeOperationalCertificate","description":"Operational Certificate","cborHex":"{cbor_hex}"}}"#
        );
        let mut f = tempfile::NamedTempFile::new().expect("tempfile");
        f.write_all(json.as_bytes()).expect("write");
        f
    }

    /// Helper: load credentials from temp files and return the vrf_skey bytes.
    fn load_vrf_skey_from_raw(raw_vrf: &[u8]) -> anyhow::Result<[u8; 32]> {
        // Generate a real KES key pair for the skey file
        let seed = [0xABu8; 32];
        let (kes_sk_bytes, kes_pk_bytes) = torsten_crypto::kes::kes_keygen(&seed).unwrap();

        // Cold key (Ed25519)
        let cold_sk = torsten_crypto::keys::PaymentSigningKey::generate();
        let cold_vk = cold_sk.verification_key().to_bytes();

        // KES vkey is always 32 bytes (the public key half of Sum6Kes)
        let kes_vkey: [u8; 32] = kes_pk_bytes[..32].try_into().unwrap();

        let (vrf_file, _) = make_vrf_skey_json(raw_vrf);
        let kes_file = make_kes_skey_json(&kes_sk_bytes);
        let opcert_file = make_opcert_json(&kes_vkey, &cold_vk);

        let creds =
            BlockProducerCredentials::load(vrf_file.path(), kes_file.path(), opcert_file.path())?;
        Ok(creds.vrf_skey)
    }

    /// cardano-cli pre-8.x VRF key files contain exactly 32 bytes (the secret seed).
    #[test]
    fn test_load_vrf_skey_32_bytes() {
        let kp = torsten_crypto::vrf::generate_vrf_keypair();
        let loaded = load_vrf_skey_from_raw(kp.secret_key())
            .expect("32-byte VRF key must load successfully");
        assert_eq!(
            loaded,
            *kp.secret_key(),
            "loaded secret key should equal the original seed"
        );
    }

    /// cardano-node / cardano-cli 8.x+ VRF key files contain 64 bytes:
    /// bytes[0..32] = secret seed, bytes[32..64] = public key.
    /// We must accept this format and use only the first 32 bytes as the seed.
    #[test]
    fn test_load_vrf_skey_64_bytes() {
        let kp = torsten_crypto::vrf::generate_vrf_keypair();
        // Construct the 64-byte expanded key as cardano-node writes it
        let mut expanded = [0u8; 64];
        expanded[..32].copy_from_slice(kp.secret_key());
        expanded[32..].copy_from_slice(&kp.public_key);

        let loaded =
            load_vrf_skey_from_raw(&expanded).expect("64-byte VRF key must load successfully");
        assert_eq!(
            loaded,
            *kp.secret_key(),
            "loaded secret seed should equal the first 32 bytes of the 64-byte key"
        );
    }

    /// The VRF proof produced from a 64-byte-encoded key must be identical
    /// to the proof produced from the 32-byte-only key, since both encode
    /// the same secret seed.
    #[test]
    fn test_vrf_proof_same_from_32_or_64_byte_key() {
        let kp = torsten_crypto::vrf::generate_vrf_keypair();
        let mut expanded = [0u8; 64];
        expanded[..32].copy_from_slice(kp.secret_key());
        expanded[32..].copy_from_slice(&kp.public_key);

        let seed_32 = load_vrf_skey_from_raw(kp.secret_key()).unwrap();
        let seed_64 = load_vrf_skey_from_raw(&expanded).unwrap();
        assert_eq!(
            seed_32, seed_64,
            "seed extracted from 32-byte and 64-byte key must be identical"
        );

        // Both seeds must produce the same VRF proof for the same input
        let input = [0x42u8; 32];
        let (proof_32, output_32) =
            torsten_crypto::vrf::generate_vrf_proof(&seed_32, &input).unwrap();
        let (proof_64, output_64) =
            torsten_crypto::vrf::generate_vrf_proof(&seed_64, &input).unwrap();
        assert_eq!(proof_32, proof_64, "VRF proofs must be identical");
        assert_eq!(output_32, output_64, "VRF outputs must be identical");
    }

    /// An invalid key length (e.g., 48 bytes) must return a clear error.
    #[test]
    fn test_load_vrf_skey_invalid_length() {
        let result = load_vrf_skey_from_raw(&[0u8; 48]);
        assert!(
            result.is_err(),
            "48-byte VRF key must be rejected as invalid"
        );
        let err = result.unwrap_err().to_string();
        assert!(
            err.contains("48"),
            "error message must include the actual length (got: {err})"
        );
    }

    #[test]
    fn test_header_hash_deterministic() {
        let creds = make_test_credentials();
        let config = BlockProducerConfig::default();
        let epoch_nonce = Hash32::from_bytes([42u8; 32]);

        let (block1, _) = forge_block(
            &creds,
            &config,
            SlotNo(1000),
            BlockNo(100),
            Hash32::ZERO,
            &epoch_nonce,
            vec![],
        )
        .unwrap();

        let (block2, _) = forge_block(
            &creds,
            &config,
            SlotNo(1000),
            BlockNo(100),
            Hash32::ZERO,
            &epoch_nonce,
            vec![],
        )
        .unwrap();

        assert_eq!(block1.header.header_hash, block2.header.header_hash);
    }

    // ─── KES key loading tests ────────────────────────────────────────────────

    /// Helper: load credentials from a raw KES key slice.
    ///
    /// Returns the loaded `BlockProducerCredentials` so callers can inspect
    /// the full credential state (not just vrf_skey as in the VRF helpers above).
    fn load_creds_with_kes(raw_kes: &[u8]) -> anyhow::Result<BlockProducerCredentials> {
        let vrf_kp = torsten_crypto::vrf::generate_vrf_keypair();
        let cold_sk = torsten_crypto::keys::PaymentSigningKey::generate();
        let cold_vk = cold_sk.verification_key().to_bytes();

        // Derive the KES public key from a fresh keypair so the opcert can
        // reference a legitimate 32-byte hot key.
        let seed = [0x11u8; 32];
        let (_kes_sk, kes_pk_bytes) = torsten_crypto::kes::kes_keygen(&seed).unwrap();
        let kes_vkey: [u8; 32] = kes_pk_bytes[..32].try_into().unwrap();

        let (vrf_file, _) = make_vrf_skey_json(vrf_kp.secret_key());
        let kes_file = make_kes_skey_json(raw_kes);
        let opcert_file = make_opcert_json(&kes_vkey, &cold_vk);

        BlockProducerCredentials::load(vrf_file.path(), kes_file.path(), opcert_file.path())
    }

    /// cardano-cli writes 608 bytes of raw KES key material to the text envelope.
    /// Loading such a file must succeed and produce a 612-byte internal buffer
    /// with the period counter initialised to zero.
    #[test]
    fn test_load_kes_skey_608_bytes_appends_period_counter() {
        let seed = [0x22u8; 32];
        let (kes_sk_612, _) = torsten_crypto::kes::kes_keygen(&seed).unwrap();
        assert_eq!(
            kes_sk_612.len(),
            torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE
        );

        // Simulate the text-envelope format: strip the 4-byte period counter.
        let kes_sk_608 = &kes_sk_612[..torsten_crypto::kes::KES_SECRET_KEY_SIZE];
        assert_eq!(kes_sk_608.len(), 608);

        let creds =
            load_creds_with_kes(kes_sk_608).expect("608-byte KES key must load successfully");

        // The resulting buffer must be 612 bytes.
        assert_eq!(
            creds.kes_skey.len(),
            torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE,
            "loaded KES skey must be padded to {} bytes",
            torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE,
        );

        // The period counter appended by the loader must be zero (period 0).
        let period =
            torsten_crypto::kes::kes_get_period(&creds.kes_skey).expect("kes_get_period must work");
        assert_eq!(
            period, 0,
            "initial KES period must be 0 after loading from text envelope"
        );
    }

    /// A key file that already has 612 bytes (e.g. written by a prior Torsten
    /// session) must be accepted as-is without modification.
    #[test]
    fn test_load_kes_skey_612_bytes_accepted_as_is() {
        let seed = [0x33u8; 32];
        let (kes_sk_612, _) = torsten_crypto::kes::kes_keygen(&seed).unwrap();

        let creds =
            load_creds_with_kes(&kes_sk_612).expect("612-byte KES key must load successfully");

        assert_eq!(
            creds.kes_skey.len(),
            torsten_crypto::kes::KES_SECRET_KEY_BUFFER_SIZE,
        );
        assert_eq!(
            creds.kes_skey, kes_sk_612,
            "612-byte key must be stored verbatim"
        );
    }

    /// An invalid KES key size must return a descriptive error.
    #[test]
    fn test_load_kes_skey_invalid_size_errors() {
        let bad_sizes: &[usize] = &[0, 32, 100, 607, 609, 611, 613, 1024];
        for &sz in bad_sizes {
            let dummy = vec![0u8; sz];
            let result = load_creds_with_kes(&dummy);
            assert!(
                result.is_err(),
                "KES key of size {sz} bytes must be rejected"
            );
            // anyhow::Error is always Debug; extract via .err()
            let err = result.err().unwrap().to_string();
            assert!(
                err.contains(&sz.to_string()),
                "error for size {sz} must mention the actual size (got: {err})"
            );
        }
    }

    /// End-to-end: load a cardano-cli-style 608-byte KES key and successfully
    /// forge a block (the forge path must evolve the key to the correct period
    /// without "Invalid kes key size" failures).
    #[test]
    fn test_forge_block_with_608_byte_kes_key() {
        let vrf_kp = torsten_crypto::vrf::generate_vrf_keypair();
        let cold_sk = torsten_crypto::keys::PaymentSigningKey::generate();
        let cold_vkey = cold_sk.verification_key().to_bytes().to_vec();

        // Generate a fresh KES keypair and strip the period counter to simulate
        // the text-envelope format written by cardano-cli.
        let seed = [0x44u8; 32];
        let (kes_sk_612, kes_pk_bytes) = torsten_crypto::kes::kes_keygen(&seed).unwrap();
        let kes_sk_608 = kes_sk_612[..torsten_crypto::kes::KES_SECRET_KEY_SIZE].to_vec();

        let kes_vkey: [u8; 32] = kes_pk_bytes[..32].try_into().unwrap();

        // Build temp files
        let (vrf_file, _) = make_vrf_skey_json(vrf_kp.secret_key());
        let kes_file = make_kes_skey_json(&kes_sk_608);
        let opcert_file = make_opcert_json(&kes_vkey, cold_vkey.as_slice().try_into().unwrap());

        let creds =
            BlockProducerCredentials::load(vrf_file.path(), kes_file.path(), opcert_file.path())
                .expect("credentials must load from 608-byte KES key");

        let config = BlockProducerConfig::default();
        let epoch_nonce = Hash32::from_bytes([0x55u8; 32]);

        // This must NOT panic with "Invalid kes key size: expected 612, got 608"
        let result = forge_block(
            &creds,
            &config,
            SlotNo(500),
            BlockNo(1),
            Hash32::ZERO,
            &epoch_nonce,
            vec![],
        );
        assert!(
            result.is_ok(),
            "forge_block must succeed with a 608-byte (cardano-cli) KES key file: {:?}",
            result.err()
        );
    }
}
