[book]
title = "Dugite Documentation"
authors = ["Sandstone Pool"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/dugite/"
git-repository-url = "https://github.com/michaeljfazio/dugite"
edit-url-template = "https://github.com/michaeljfazio/dugite/edit/main/docs/{path}"
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-hierarchical-headings = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = false
